server:
  port: 8080
  error:
    include-message: always

spring:
#creates/instantiates datasource object to make connections to the database
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: potatochip
    password: password
#ddl-auto initiates the database and defines how your database schema is handled
#hibernate is a java framework and ORM tool used to implement JPA methods/interacting with
  #different types of databases
#jdbc allows java programs to connect to PostgreSQL database using database independent java code
  jpa:
    hibernate:
      #creates schema then destroys it after program is done executing so getting fresh data at every restart
      #if we want the data to persist then it would just be "ddl-auto: update"
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
  flyway:
    clean-disabled: false